"""
Secret Manager fetch for the portable auth state (auth_state.json). No-op
locally — only exercised when K_SERVICE is set (i.e. running on Cloud Run).

auth_state.json is a live LinkedIn session (Playwright storage_state export),
not a password — it's the thing that actually needs protecting in the cloud.
LINKEDIN_EMAIL/LINKEDIN_PASSWORD are not read by any code (login is manual
only) and don't need a cloud secret at all.

There is no automated way to refresh this secret: it's re-generated by
running `save_session.py` locally (interactive login) and the resulting
auth_state.json is uploaded as a new Secret Manager version by hand. See
CLAUDE.md for the re-auth procedure.
"""

import os

GCP_PROJECT = os.getenv("GCP_PROJECT")
AUTH_STATE_SECRET = os.getenv("AUTH_STATE_SECRET", "linkedin-auth-state")


def fetch_auth_state(local_path: str) -> None:
    if os.path.isfile(local_path):
        return  # already present (e.g. mounted volume) — don't overwrite

    from google.cloud import secretmanager
    client = secretmanager.SecretManagerServiceClient()
    name = f"projects/{GCP_PROJECT}/secrets/{AUTH_STATE_SECRET}/versions/latest"
    print(f"[cloud_auth] Fetching auth state from {name}")
    response = client.access_secret_version(request={"name": name})
    with open(local_path, "wb") as f:
        f.write(response.payload.data)
